export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const REPORT_SPAM = 'REPORT_SPAM';
export const POST_LIKES = 'POST_LIKES';
export const COMMENT_LIKES = 'COMMENT_LIKES';
export const REPLY_LIKES = 'REPLY_LIKES';
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const SUGGESTION_RECEIVED = 'SUGGESTION_RECEIVED';